FROM public.ecr.aws/lambda/python:3.11

WORKDIR ${LAMBDA_TASK_ROOT}

COPY requirements-lambda.txt .
RUN pip install --upgrade pip && \
    pip install --no-cache-dir -r requirements-lambda.txt

COPY app ./app
COPY aws_chroma_db ./aws_chroma_db
COPY patent_review.db ./patent_review.db

CMD ["app.main.handler"]